apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: lxp-tampermonkey-demo
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        # 增加啟動超時時間
        run.googleapis.com/startup-cpu-boost: 'true'
        # 容器併發設定
        autoscaling.knative.dev/maxScale: '10'
        autoscaling.knative.dev/minScale: '0'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: PLACEHOLDER_IMAGE
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        resources:
          limits:
            cpu: '1000m'
            memory: 512Mi
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 0
          timeoutSeconds: 1
          periodSeconds: 3
          successThreshold: 1
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
  traffic:
  - percent: 100
    latestRevision: true
